### ISSUE TITLE
Use DESTDIR, fix 'install -o root -g root', etc.

### ISSUE THREAD

**Issue by nkadel** [tootedom/authbind-centos-rpm#2]
I've just reviewed your .spec file, and started form it to produce a much cleaner one with these features:
- Use _lib, _libdir, _sysconfdir, and _prefix loaded into the Makefile, instead of working manually around rpmmacro values.
- Enable and use 'DESTDIR' for 'make install' and 'make install-man'
- Set configuration directories from /etc as configuration directories only.
- Explicitly set suid permissions for the inaries

If you'd like the file, I'd be happy to send it.

**Comment by tootedom** [comment]
Send it on through for sure.
thank you.

**Comment by nkadel** [comment]
It's pull request number 3.

**Comment by tootedom** [comment]
merged, in and applied a couple of fixes to the spec and the patch file.
Hopefully that works for you.
/dom

**Comment by nkadel** [comment]
Looks good, let's close it.
